[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | node_modules
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 100